<div id="apropos"> 
    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title">Qui suis-je ?</p>
                <p>Découvrez-moi !</p>
            </div>
            <div class="flip-card-back">
                <li class="title">
                    <a>Curieux</a><br>
                    <a>Passionné</a><br>
                    <a>Rigoureux</a><br>
                    <a>Sens du travail</a><br>
                    <a>Ponctuel</a><br>
                    <a>Force de Proposition</a>
                </li>
            </div>
        </div>
    </div>
</div>