<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="<?= $env_name ?>">
<meta name="description" content="<?= $env_desc ?>"/>
<meta property="og:title" content="<?= $env_name ?>"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="<?= $env_url ?>"/>
<meta property="og:image" content="<?= $env_url ."/". $env_logo ?>"/>
<meta property="og:description" content="<?= $env_desc ?>"/>