<nav>
    <ul class="nav justify-content-end">
        <li class="nav-item name">
            Kevin MUZIAK
        </li>
        <li class="nav-item">
            <button class="cta">
                <span class="hover-underline-animation"> A Propos </span>
                <svg
                    id="arrow-horizontal"
                    xmlns="http://www.w3.org/2000/svg"
                    width="30"
                    height="10"
                    viewBox="0 0 46 16"
                >
                <path
                id="Path_10"
                data-name="Path 10"
                d="M8,0,6.545,1.455l5.506,5.506H-30V9.039H12.052L6.545,14.545,8,16l8-8Z"
                transform="translate(30)"
                ></path>
                </svg>
            </button>
        </li>
        <li class="nav-item">
        <button class="cta">
                <span class="hover-underline-animation"> Mes Projets </span>
                <svg
                    id="arrow-horizontal"
                    xmlns="http://www.w3.org/2000/svg"
                    width="30"
                    height="10"
                    viewBox="0 0 46 16"
                >
                <path
                id="Path_10"
                data-name="Path 10"
                d="M8,0,6.545,1.455l5.506,5.506H-30V9.039H12.052L6.545,14.545,8,16l8-8Z"
                transform="translate(30)"
                ></path>
                </svg>
            </button>
        </li>
        <li class="nav-item">
        <button class="cta">
                <span class="hover-underline-animation"> Me Contacter </span>
                <svg
                    id="arrow-horizontal"
                    xmlns="http://www.w3.org/2000/svg"
                    width="30"
                    height="10"
                    viewBox="0 0 46 16"
                >
                <path
                id="Path_10"
                data-name="Path 10"
                d="M8,0,6.545,1.455l5.506,5.506H-30V9.039H12.052L6.545,14.545,8,16l8-8Z"
                transform="translate(30)"
                ></path>
                </svg>
            </button>
        </li>
    </ul>
</nav>
